import type { Job, Candidate } from '@/lib/types';

export const jobs: Job[] = [
  {
    id: '1',
    title: 'Frontend Developer',
    company: 'Innovate Inc.',
    logoUrl: 'https://placehold.co/100x100.png?text=I',
    location: 'San Francisco, CA',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryMin: 120000,
    salaryMax: 150000,
    description: `Innovate Inc. is seeking a skilled Frontend Developer to join our dynamic team. You will be responsible for building the ‘client-side’ of our web applications. You should be able to translate our company and customer needs into functional and appealing interactive applications. We expect you to be a tech-savvy professional, who is curious about new digital technologies and aspires to combine usability with visual design. You should be proficient in React, TypeScript, and modern CSS frameworks.`,
    applyUrl: '#',
    deadline: new Date('2024-12-31'),
    skills: ['React', 'TypeScript', 'CSS'],
  },
  {
    id: '2',
    title: 'Backend Engineer',
    company: 'Amazon',
    logoUrl: 'https://placehold.co/100x100.png?text=A',
    location: 'New York, NY',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 150000,
    salaryMax: 180000,
    description: `DataSolutions is looking for an experienced Backend Engineer to help us build and maintain the server-side logic of our applications. You will work with our team of talented engineers to design and implement scalable, secure, and reliable services. The ideal candidate has strong experience with Node.js, PostgreSQL, and cloud services like AWS or Google Cloud. A strong understanding of database design and API development is crucial.`,
    applyUrl: '#',
    deadline: new Date('2024-11-30'),
    skills: ['Node.js', 'PostgreSQL', 'AWS'],
  },
  {
    id: '3',
    title: 'UX/UI Designer',
    company: 'Adobe',
    logoUrl: 'https://placehold.co/100x100.png?text=Ad',
    location: 'Remote',
    type: 'Contract',
    experienceLevel: 'Mid-level',
    salaryMin: 80000,
    salaryMax: 100000,
    description: `Creative Co. needs a talented UX/UI Designer to create amazing user experiences. The ideal candidate should have an eye for clean and artful design, possess superior UI skills and be able to translate high-level requirements into interaction flows and artifacts. They will be working closely with our product and engineering teams. A strong portfolio of successful UX/UI design projects is required. Proficiency in Figma, Sketch, and Adobe Creative Suite is a must.`,
    applyUrl: '#',
    deadline: new Date('2024-10-15'),
    skills: ['Figma', 'Sketch', 'Adobe Suite'],
  },
  {
    id: '4',
    title: 'Data Science Intern',
    company: 'Google',
    logoUrl: 'https://placehold.co/100x100.png?text=G',
    location: 'Boston, MA',
    type: 'Internship',
    experienceLevel: 'Entry',
    salaryMin: 50000,
    salaryMax: 60000,
    description: `Alpha Analytics is excited to offer a Data Science Internship for aspiring data scientists. This is a great opportunity to work on real-world projects and gain hands-on experience in machine learning, data analysis, and predictive modeling. You will assist our senior data scientists in collecting data, building models, and presenting findings. Candidates should be pursuing a degree in Computer Science, Statistics, or a related field and have a basic understanding of Python and SQL.`,
    applyUrl: '#',
    deadline: new Date('2024-09-30'),
    skills: ['Python', 'SQL', 'Machine Learning'],
  },
   {
    id: '5',
    title: 'Product Manager',
    company: 'Microsoft',
    logoUrl: 'https://placehold.co/100x100.png?text=M',
    location: 'Austin, TX',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryMin: 140000,
    salaryMax: 170000,
    description: `NextGen Products is on the hunt for a visionary Product Manager to drive the development of our next-generation software solutions. You will be responsible for the product planning and execution throughout the Product Lifecycle, including gathering and prioritizing product and customer requirements, defining the product vision, and working closely with engineering, sales, marketing, and support to ensure revenue and customer satisfaction goals are met. Proven experience in product management and a technical background are essential.`,
    applyUrl: '#',
    deadline: new Date('2025-01-15'),
    skills: ['Product Management', 'Agile', 'Roadmapping'],
  },
  {
    id: '6',
    title: 'Marketing Specialist',
    company: 'Zoho',
    logoUrl: 'https://placehold.co/100x100.png?text=Z',
    location: 'Remote',
    type: 'Part-time',
    experienceLevel: 'Mid-level',
    salaryMin: 60000,
    salaryMax: 75000,
    description: `Growth Gurus is seeking a creative and data-driven Marketing Specialist to join our remote team. You'll be responsible for developing and implementing marketing strategies to increase brand awareness and drive lead generation. Your role will involve content creation, social media management, SEO, and campaign analysis. We are looking for someone with a passion for marketing and a proven track record of success in digital marketing campaigns.`,
    applyUrl: '#',
    deadline: new Date('2024-11-01'),
    skills: ['SEO', 'Content Creation', 'Social Media'],
  },
];

export const candidates: Candidate[] = [
  {
    id: 'cand1',
    name: 'Alice Johnson',
    title: 'Senior Frontend Developer',
    imageUrl: 'https://placehold.co/100x100.png?text=A',
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL', 'Storybook'],
    summary: 'A seasoned frontend developer with 8 years of experience building scalable and user-friendly web applications. Passionate about creating performant and accessible UIs.'
  },
  {
    id: 'cand2',
    name: 'Bob Williams',
    title: 'Lead Backend Engineer',
    imageUrl: 'https://placehold.co/100x100.png?text=B',
    skills: ['Node.js', 'Go', 'PostgreSQL', 'Kubernetes', 'AWS', 'Microservices'],
    summary: 'Lead engineer specializing in distributed systems and cloud infrastructure. Proven track record of designing and deploying high-availability services that handle millions of requests.'
  },
  {
    id: 'cand3',
    name: 'Charlie Brown',
    title: 'Creative UX/UI Designer',
    imageUrl: 'https://placehold.co/100x100.png?text=C',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Interaction Design'],
    summary: 'A creative and user-centric designer who bridges the gap between user needs and business goals. Experienced in leading design on projects from concept to launch.'
  }
];
